### PR TITLE
Amending Incorrect Argument to Relationship Point Update

### LINKED ISSUE #365: Pledging to the Apes Causes TM Point-Related Crash
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Scene number

Dunno; it's the scene where you choose which frat to pledge to

### Priority

High

### Bug Description

_**PLAYING ON STEAM RELEASE VERSION**_

Went to pledge to the Apes and had a full-screen game crash 
image

### Expected behavior

_No response_

### Additional context

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/v7/v7.rpy", line 4690, in <module>
  File "game/reputation.rpy", line 69, in add_point
KeyError: <Reputations.TROUBLEMAKER: 'troublemaker'>

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "v7/v7.rpyc", line 4690, in script
  File "C:\Program Files (x86)\Steam\steamapps\common\College Kings\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files (x86)\Steam\steamapps\common\College Kings\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/v7/v7.rpy", line 4690, in <module>
  File "game/reputation.rpy", line 69, in add_point
KeyError: <Reputations.TROUBLEMAKER: 'troublemaker'>

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
College Kings 1.2.11s (SHA: c1312df2a)
Sun Apr 30 01:43:21 2023
```

### What is the OS version you are playing on?

Windows

### PR DESCRIPTION
**Pull request by Chinay-Domitrix**
Fixes #365

### CODE REVIEW

**Comment by KiloOscarSix** [comment]
Please avoid committing submodules, if you have submodules that are showing up then you might be on the wrong branch

**Review by KiloOscarSix — APPROVED** [review]
LGTM

**Comment by Chinay-Domitrix** [comment]
> Please avoid committing submodules, if you have submodules that are showing up then you might be on the wrong branch

It was an old commit I couldn't remove because it was messing with other files 🫤

**Comment by KiloOscarSix** [comment]
Aye, doesn't cause any serious problems just a pain to have to create another commit to fix the submodule versions

**Pull request merged**
